### ISSUE TITLE
Add a license declaration

### ISSUE THREAD

**Issue by phihag** [ravishi/rdio-dl#4]
Currently, there is no license declaration for rdio-dl. I assume that I am allowed to view the source, but there is no statement of whether and how I am allowed to use, modify, and distribute it. There should be a license declaration (as a file `LICENSE` and/or just the name in `setup.py`), preferably [Unlicense](http://unlicense.org).

**Comment by ravishi** [comment]
Fixed in b7e9b32f7c7458a902421ae162dffbe886491310.
