### ISSUE TITLE
File tagging and Image embedding.

### ISSUE THREAD

**Issue by smartpunter** [ravishi/rdio-dl#9]
I spent 4 hours trying to implement this myself, but i am nodejs programmer, not python.

Please, add ID3 tagging for files that should be really simple, as you have all necessary data passed from RDIO. Maybe adding image should be made optional, but is definitely necessary.

You can use this library to insert data into downloaded file: http://eyed3.nicfit.net/

Also, sometimes rdio returns data like this: 

{u'display_id': u't2885517', u'extractor': u'Rdio', 'description': u'', u'format': u'0 - unknown', u'requested_subtitles': None, 'uploader': u'Avril Lavigne', u'format_id': u'0', 'id': u't2885517', u'playlist_title': u'Download', u'playlist': u'Download', u'thumbnails': [{u'url': u'http://rdio3img-a.akamaihd.net/album/3/7/0/000000000003a073/2/square-200.jpg', u'id': u'0'}], 'title': u'Tomorrow', 'url': None, u'extractor_key': u'Rdio', u'playlist_index': 501, u'playlist_id': u'p15373267', 'ext': u'mp3', u'webpage_url_basename': u'Rl66A3wrfkbJ', u'webpage_url': u'http://rd.io/x/Rl66A3wrfkbJ/', 'thumbnail': u'http://rdio3img-.akamaihd.net/album/3/7/0/000000000003a073/2/square-200.jpg', u'n_entries': 920}

Which makes script to fail, please add checking that url is defined.

Hope it won't take long to implement, rdio is closing soon and i really want to save my collection with tags and pictures before.

Thank you for great script and sharing!

**Comment by ravishi** [comment]
Hello, there.

There is some working code in the current `id3-tagging` branch. Unfortunately, it won't work for high quality aac mp4 downloads, only for mp3 ones. I'll take some time to explore the mp4 tagging options before publishing it on master.

**Comment by smartpunter** [comment]
Just checked, works like a charm.
To make it perfect, it shouldn't be that hard to retrieve and embed to song file cover image (from 'thumbnails' key).

**Comment by zhoul-HS** [comment]
oh my tagging on high quality aac mp4 will be amaaaaazing!

**Comment by ravishi** [comment]
I've pushed some code to master that will enable thumbnail and metadata embedding to all file formats. You can enable it through the `--embed-thumbnails`' flag. It uses ffmpeg to write the metadata to the files. It also needs AtomicParsley to write the thumbnails to m4a files.
